Lean js project
OfficeDev/Office-Addin-TaskPane-JS pull request #77
Opened 2021-04-26 18:49 UTC by millerds

Remove references to typescript packages that are just used for testing and tests are deleted when making the template.

2021-04-26 18:59 UTC, akrantz requested changes
These changes look good.  

But in looking at the result after convert-to-single-host is run:

1. is the tsconfig file needed?
2. ts-loader is still in devDependencies
3. "npm run lint" gives error: Error: Failed to load parser '@typescript-eslint/parser' declared in '--config': Cannot find module 'typescript'

2021-04-26 20:45 UTC, millerds commented
Looks like the lint call uses the shared office-addin-lint script which uses typescript-eslint which requires typescript to be installed (apparently not something automatically gotten with the package).  This also requires the tsconfig file (removing that causes a different linter break).  I'm not sure if I can override the office-addin-lint parser to not be the typescript one . . . otherwise it would have to be a more extensive change to break completely with typescript (update the shared script to be able to do one or the other, make the template not use the shared script, or something else).

2021-04-30 17:42 UTC, millerds commented
@akrantz any further comments?

2021-04-30 18:02 UTC, akrantz approved these changes

2021-04-30 18:08 UTC, merged